repos:
  - repo: local
    hooks:
      - id: rustfmt
        exclude: ^.github/|^.gitmessage|.md
        name: rustfmt
        description: Check if all files follow the rustfmt style
        entry: cargo fmt --all
        language: system
        pass_filenames: false
      - id: cargo-test
        exclude: ^.github/|^.gitmessage|.md
        name: Cargo test
        entry: cargo test -- --nocapture
        language: system
        pass_filenames: false
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-merge-conflict
