[package]
name = "rast"
version = "0.0.1"
edition = "2021"
description = "A formattable Rust AST"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
conversion = ["dep:proc-macro2", "dep:quote"]

[dependencies]
proc-macro2 = { version = "1.0", optional = true }
quote = { version = "1.0", optional = true }
